import { calculateQuote, type PricingCatalog, type PricingValue } from '../src';

type Field = { key:string; label:string; type:'number'|'boolean'; value:number|boolean; min?:number; step?:number };
type Scenario = { label:string; catalog:PricingCatalog; fields:Field[] };
const scenarios:Record<string,Scenario>={
  locksmith:{label:'Mobile locksmith',catalog:{currency:'USD',items:[{id:'unlock',label:'Vehicle lockout',baseAmount:8500},{id:'rekey',label:'Residential rekey',baseAmount:4500}],rules:[{id:'mileage',label:'Travel beyond 15 miles',type:'per_unit',input:'distance',rate:200,includedUnits:15},{id:'after-hours',label:'After-hours service',type:'fixed',amount:4000,condition:{attribute:'afterHours',operator:'eq',value:true}}]},fields:[{key:'distance',label:'Travel distance (miles)',type:'number',value:24,min:0,step:1},{key:'afterHours',label:'After-hours appointment',type:'boolean',value:false}]},
  lawn:{label:'Lawn service',catalog:{currency:'USD',items:[{id:'mow',label:'Lawn mowing',baseAmount:3000},{id:'cleanup',label:'Seasonal cleanup',baseAmount:7500}],rules:[{id:'acreage',label:'Additional acreage',type:'per_unit',input:'acres',rate:6000,includedUnits:.5},{id:'bagging',label:'Bag and remove clippings',type:'fixed',amount:1500,condition:{attribute:'bagging',operator:'eq',value:true}}]},fields:[{key:'acres',label:'Property size (acres)',type:'number',value:1.5,min:0,step:.25},{key:'bagging',label:'Bag and remove clippings',type:'boolean',value:true}]},
  creative:{label:'Creative studio',catalog:{currency:'USD',items:[{id:'landing',label:'Landing page design',baseAmount:120000},{id:'identity',label:'Visual identity package',baseAmount:180000}],rules:[{id:'rush',label:'Rush delivery',type:'percentage',percent:20,condition:{attribute:'rush',operator:'eq',value:true}},{id:'revisions',label:'Additional revision rounds',type:'per_unit',input:'revisions',rate:15000,includedUnits:2}]},fields:[{key:'revisions',label:'Revision rounds',type:'number',value:3,min:0,step:1},{key:'rush',label:'Rush delivery',type:'boolean',value:false}]}
};
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const scenario=$<HTMLSelectElement>('scenario'),item=$<HTMLSelectElement>('item'),fields=$('fields'),lines=$('lines'),total=$('total'),config=$('config');
Object.entries(scenarios).forEach(([key,s])=>scenario.add(new Option(s.label,key)));
function setup(){const s=scenarios[scenario.value];item.innerHTML='';s.catalog.items.forEach(x=>item.add(new Option(x.label,x.id)));fields.innerHTML='';s.fields.forEach(f=>{const label=document.createElement('label');if(f.type==='boolean'){label.className='check';label.innerHTML=`<input type="checkbox" data-key="${f.key}" ${f.value?'checked':''}>${f.label}`;}else label.innerHTML=`${f.label}<input type="number" data-key="${f.key}" value="${f.value}" min="${f.min??0}" step="${f.step??1}">`;fields.append(label)});fields.querySelectorAll('input').forEach(x=>x.addEventListener('input',render));item.addEventListener('change',render);render()}
function render(){const s=scenarios[scenario.value],attributes:Record<string,PricingValue>={};fields.querySelectorAll<HTMLInputElement>('input').forEach(x=>attributes[x.dataset.key!]=x.type==='checkbox'?x.checked:Number(x.value));try{const q=calculateQuote(s.catalog,{itemId:item.value,attributes});const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:q.currency}).format(n/100);lines.innerHTML=q.lines.map(x=>`<div class="line"><div>${x.label}<small>${x.kind.replace('_',' ')}</small></div><strong>${money(x.amount)}</strong></div>`).join('');total.textContent=money(q.total);config.textContent=JSON.stringify({catalog:s.catalog,request:{itemId:item.value,attributes}},null,2)}catch(e){lines.textContent=e instanceof Error?e.message:'Unable to calculate quote';total.textContent='—'}}
scenario.addEventListener('change',setup);setup();
