import { calculateQuote, type PricingCatalog, type PricingInput, type PricingRule, type PricingValue } from '../src';
type State={businessName:string;catalog:PricingCatalog};
const storageKey='pricing-tool-builder-v1';
const blank=():State=>({businessName:'My Business',catalog:{currency:'USD',items:[{id:'service',label:'My service',baseAmount:7500}],inputs:[],rules:[]}});
const example=():State=>({businessName:'Ridge Mobile Services',catalog:{currency:'USD',items:[{id:'vehicle-lockout',label:'Vehicle lockout',baseAmount:8500},{id:'home-lockout',label:'Home lockout',baseAmount:9500}],inputs:[{key:'distanceMiles',label:'Travel distance',type:'number',unit:'miles',min:0,step:1,defaultValue:12,required:true},{key:'afterHours',label:'After-hours appointment',type:'boolean',defaultValue:false}],rules:[{id:'mileage',label:'Travel beyond 15 miles',type:'per_unit',input:'distanceMiles',rate:200,includedUnits:15},{id:'after-hours',label:'After-hours service',type:'fixed',amount:4000,condition:{attribute:'afterHours',operator:'eq',value:true}}]}});
let state:State=load();
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const esc=(v:unknown)=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]!));
const slug=(v:string,f:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||f;
const cents=(v:string)=>Math.round(Number(v||0)*100);
const dollars=(v:number)=>(v/100).toFixed(2);
function load():State{try{return JSON.parse(localStorage.getItem(storageKey)||'null')||blank()}catch{return blank()}}
function save(){localStorage.setItem(storageKey,JSON.stringify(state));$('save-state').textContent='Saved in this browser';$('config').textContent=JSON.stringify(state,null,2)}
function opt(value:string,label:string,current:string){return '<option value="'+esc(value)+'" '+(value===current?'selected':'')+'>'+esc(label)+'</option>'}
function show(tab:string){document.querySelectorAll<HTMLElement>('.panel').forEach(x=>x.classList.toggle('active',x.id===tab));document.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));if(tab==='preview')renderPreview();if(tab==='transfer')$('config').textContent=JSON.stringify(state,null,2)}
function render(){($<HTMLInputElement>('business-name')).value=state.businessName;($<HTMLSelectElement>('currency')).value=state.catalog.currency;renderServices();renderInputs();renderRules();save()}
function renderServices(){const root=$('services');root.innerHTML=state.catalog.items.map((x,i)=>'<div class="editor-row" data-kind="service" data-index="'+i+'"><label>Service name<input data-field="label" value="'+esc(x.label)+'"></label><label>Base price<input data-field="baseAmount" type="number" min="0" step=".01" value="'+dollars(x.baseAmount)+'"></label><label>Internal ID<input data-field="id" value="'+esc(x.id)+'"></label><button class="remove" data-remove="service">Remove</button></div>').join('')||'<div class="empty">Add at least one service.</div>'}
function renderInputs(){const root=$('inputs');root.innerHTML=(state.catalog.inputs??[]).map((x:any,i)=>{let extra='';if(x.type==='number')extra='<label>Unit<input data-field="unit" value="'+esc(x.unit??'')+'"></label>';else if(x.type==='select')extra='<label>Choices<input data-field="options" value="'+esc(x.options.map((o:any)=>o.label).join(', '))+'"></label>';else extra='<label>Default<select data-field="defaultValue">'+opt('false','No',String(x.defaultValue??false))+opt('true','Yes',String(x.defaultValue??false))+'</select></label>';return '<div class="editor-row wide" data-kind="input" data-index="'+i+'"><label>Question<input data-field="label" value="'+esc(x.label)+'"></label><label>Type<select data-field="type">'+opt('number','Number',x.type)+opt('boolean','Yes / no',x.type)+opt('select','Multiple choice',x.type)+'</select></label><label>Key<input data-field="key" value="'+esc(x.key)+'"></label>'+extra+'<button class="remove" data-remove="input">Remove</button></div>'}).join('')||'<div class="empty">Add a question when a customer answer changes the price.</div>'}
function renderRules(){const inputs=state.catalog.inputs??[];const choices=(current:string,booleans=false)=>'<option value="">No condition</option>'+inputs.filter(x=>!booleans||x.type==='boolean').map(x=>opt(x.key,x.label,current)).join('');$('rules').innerHTML=(state.catalog.rules??[]).map((x:any,i)=>{let amount=0,linked='',extra='';if(x.type==='fixed'){amount=x.amount;linked=x.condition?.attribute??'';extra='<label>Apply when<select data-field="linked">'+choices(linked,true)+'</select></label>'}else if(x.type==='per_unit'){amount=x.rate;linked=x.input;extra='<label>Question<select data-field="linked">'+choices(linked)+'</select></label><label>Included units<input data-field="includedUnits" type="number" min="0" step=".1" value="'+(x.includedUnits??0)+'"></label>'}else{amount=x.percent;linked=x.condition?.attribute??'';extra='<label>Apply when<select data-field="linked">'+choices(linked,true)+'</select></label>'}return '<div class="editor-row wide" data-kind="rule" data-index="'+i+'"><label>Rule name<input data-field="label" value="'+esc(x.label)+'"></label><label>Type<select data-field="type">'+opt('fixed','Fixed fee',x.type)+opt('per_unit','Per unit',x.type)+opt('percentage','Percentage',x.type)+'</select></label><label>'+(x.type==='percentage'?'Percent':'Amount')+'<input data-field="value" type="number" min="0" step="'+(x.type==='percentage'?'.1':'.01')+'" value="'+(x.type==='percentage'?amount:dollars(amount))+'"></label>'+extra+'<button class="remove" data-remove="rule">Remove</button></div>'}).join('')||'<div class="empty">No rules yet. Quotes use the service base price.</div>'}
function update(el:HTMLInputElement|HTMLSelectElement){const row=el.closest<HTMLElement>('[data-kind]');if(!row)return;const i=Number(row.dataset.index),field=el.dataset.field!,kind=row.dataset.kind;if(kind==='service'){const x:any=state.catalog.items[i];x[field]=field==='baseAmount'?cents(el.value):el.value}if(kind==='input'){let x:any=state.catalog.inputs![i];if(field==='type'){const base={key:x.key,label:x.label,type:el.value};x=el.value==='number'?{...base,min:0,step:1,defaultValue:0}:el.value==='boolean'?{...base,defaultValue:false}:{...base,options:[{label:'Option 1',value:'Option 1'}]};state.catalog.inputs![i]=x;renderInputs();renderRules()}else if(field==='options')x.options=el.value.split(',').map(v=>v.trim()).filter(Boolean).map(v=>({label:v,value:v}));else if(field==='defaultValue'&&x.type==='boolean')x.defaultValue=el.value==='true';else x[field]=el.value}if(kind==='rule'){const rules=state.catalog.rules!,x:any=rules[i];if(field==='type'){const base={id:x.id,label:x.label};rules[i]=el.value==='fixed'?{...base,type:'fixed',amount:0}:el.value==='per_unit'?{...base,type:'per_unit',input:'',rate:0,includedUnits:0}:{...base,type:'percentage',percent:0};renderRules()}else if(field==='value'){if(x.type==='fixed')x.amount=cents(el.value);else if(x.type==='per_unit')x.rate=cents(el.value);else x.percent=Number(el.value)}else if(field==='linked'){if(x.type==='per_unit')x.input=el.value;else x.condition=el.value?{attribute:el.value,operator:'eq',value:true}:undefined}else if(field==='includedUnits')x.includedUnits=Number(el.value);else x[field]=el.value}save()}
function add(kind:string){if(kind==='service')state.catalog.items.push({id:'service-'+(state.catalog.items.length+1),label:'New service',baseAmount:0});if(kind==='input'){state.catalog.inputs??=[];const n=state.catalog.inputs.length+1;state.catalog.inputs.push({key:'question'+n,label:'New question',type:'number',min:0,step:1,defaultValue:0})}if(kind==='rule'){state.catalog.rules??=[];const n=state.catalog.rules.length+1;state.catalog.rules.push({id:'rule-'+n,label:'New fee',type:'fixed',amount:0})}render()}
function fieldMarkup(x:PricingInput){if(x.type==='boolean')return '<label class="check-field"><input data-quote="'+esc(x.key)+'" type="checkbox" '+(x.defaultValue?'checked':'')+'>'+esc(x.label)+'</label>';if(x.type==='select')return '<label>'+esc(x.label)+'<select data-quote="'+esc(x.key)+'">'+x.options.map(o=>opt(String(o.value),o.label,String(x.defaultValue??o.value))).join('')+'</select></label>';return '<label>'+esc(x.label)+(x.unit?' ('+esc(x.unit)+')':'')+'<input data-quote="'+esc(x.key)+'" type="number" value="'+(x.defaultValue??'')+'" min="'+(x.min??'')+'" max="'+(x.max??'')+'" step="'+(x.step??1)+'"></label>'}
function renderPreview(){const item=$<HTMLSelectElement>('quote-item');item.innerHTML=state.catalog.items.map(x=>opt(x.id,x.label,item.value)).join('');if(!item.value&&state.catalog.items[0])item.value=state.catalog.items[0].id;$('preview-title').textContent=state.businessName+' estimate';$('quote-fields').innerHTML=(state.catalog.inputs??[]).map(fieldMarkup).join('');document.querySelectorAll<HTMLInputElement|HTMLSelectElement>('[data-quote]').forEach(x=>x.oninput=calculate);item.oninput=calculate;$<HTMLInputElement>('quote-quantity').oninput=calculate;calculate()}
function calculate(){const attributes:Record<string,PricingValue>={};document.querySelectorAll<HTMLInputElement|HTMLSelectElement>('[data-quote]').forEach(el=>{const x=state.catalog.inputs?.find(i=>i.key===el.dataset.quote);if(x)attributes[x.key]=x.type==='boolean'?(el as HTMLInputElement).checked:x.type==='number'?Number(el.value):el.value});try{const q=calculateQuote(state.catalog,{itemId:$<HTMLSelectElement>('quote-item').value,quantity:Number($<HTMLInputElement>('quote-quantity').value),attributes});const format=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:q.currency}).format(n/100);$('quote-lines').innerHTML=q.lines.map(x=>'<div class="quote-line"><div>'+esc(x.label)+'<small>'+x.kind.replace('_',' ')+'</small></div><strong>'+format(x.amount)+'</strong></div>').join('');$('quote-total').textContent=format(q.total);$('quote-error').textContent=''}catch(e){$('quote-lines').innerHTML='';$('quote-total').textContent='—';$('quote-error').textContent=e instanceof Error?e.message:'Unable to calculate quote'}}
document.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(x=>x.onclick=()=>show(x.dataset.tab!));document.querySelectorAll<HTMLButtonElement>('[data-go]').forEach(x=>x.onclick=()=>show(x.dataset.go!));
$('add-service').onclick=()=>add('service');$('add-input').onclick=()=>add('input');$('add-rule').onclick=()=>add('rule');$('load-example').onclick=()=>{state=example();render()};
$('business-name').addEventListener('input',e=>{state.businessName=(e.target as HTMLInputElement).value;save()});$('currency').addEventListener('change',e=>{state.catalog.currency=(e.target as HTMLSelectElement).value;save()});$('setup').addEventListener('input',e=>update(e.target as HTMLInputElement));$('setup').addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-remove]');if(!b)return;const i=Number(b.closest<HTMLElement>('[data-index]')!.dataset.index);if(b.dataset.remove==='service')state.catalog.items.splice(i,1);if(b.dataset.remove==='input'){const removed=state.catalog.inputs?.[i]?.key;state.catalog.inputs?.splice(i,1);state.catalog.rules=(state.catalog.rules??[]).map(rule=>{if(rule.type==='per_unit'&&rule.input===removed)return {...rule,input:''};if(rule.condition?.attribute===removed){const copy={...rule};delete copy.condition;return copy}return rule})}if(b.dataset.remove==='rule')state.catalog.rules?.splice(i,1);render()});
$('export-json').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=slug(state.businessName,'pricing')+'-pricing.json';a.click();URL.revokeObjectURL(a.href)};
$<HTMLInputElement>('import-json').onchange=async e=>{const file=(e.target as HTMLInputElement).files?.[0];if(!file)return;try{const imported=JSON.parse(await file.text());if(!imported.catalog?.items?.length)throw new Error();state=imported;render();show('setup')}catch{alert('That file is not a valid pricing configuration.')}};
$('reset').onclick=()=>{if(confirm('Clear this pricing setup and start over?')){state=blank();render();show('setup')}};render();
